function DIP_GUI()
clc; clear; close all;

img_rgb = imread('../images/input/dip_img.jpeg');

fig = figure('Name','DIP Image Enhancement System',...
    'NumberTitle','off','Position',[100 100 500 420]);

uicontrol('Style','text','String','DIP Image Enhancement System',...
    'Position',[50 360 400 40],'FontSize',14,'FontWeight','bold',...
    'BackgroundColor',[0.95 0.95 0.95]);

uicontrol('Style','pushbutton','String','Phase 1 — Acquisition',...
    'Position',[50 290 180 50],'FontSize',11,...
    'Callback',@(~,~) phase1_basics(img_rgb));

uicontrol('Style','pushbutton','String','Phase 2 — Sampling',...
    'Position',[270 290 180 50],'FontSize',11,...
    'Callback',@(~,~) phase2_sampling(img_rgb));

uicontrol('Style','pushbutton','String','Phase 3 — Geometric',...
    'Position',[50 220 180 50],'FontSize',11,...
    'Callback',@(~,~) phase3_geometric(img_rgb));

uicontrol('Style','pushbutton','String','Phase 4 — Intensity',...
    'Position',[270 220 180 50],'FontSize',11,...
    'Callback',@(~,~) phase4_intensity(img_rgb));

uicontrol('Style','pushbutton','String','Phase 5 — Histogram',...
    'Position',[50 150 180 50],'FontSize',11,...
    'Callback',@(~,~) phase5_histogram(img_rgb));

uicontrol('Style','pushbutton','String','Phase 6 — Full Pipeline',...
    'Position',[270 150 180 50],'FontSize',11,...
    'Callback',@(~,~) process_image(img_rgb));

uicontrol('Style','text','String','Click Button!',...
    'Position',[50 90 400 30],'FontSize',10,...
    'ForegroundColor',[0.4 0.4 0.4],'BackgroundColor',[0.95 0.95 0.95]);
end